# Generated by Django 5.0.6 on 2024-10-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.CharField(default='SemValorInserido', max_length=100)),
                ('cpfResponsavel', models.CharField(max_length=30)),
                ('password', models.CharField(default='pbkdf2_sha256$720000$5QQTMekqhhUaI2caV3L3dD$3jRNqSf5ykmdul9mO7kHz4eOz5LKRuuBU+q/xJCZqnQ=', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataValid', models.DateField()),
                ('marca', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField()),
                ('frete', models.CharField(choices=[('CIF', 'CIF'), ('FOB', 'FOB')], default='CIF', max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagem', models.ImageField(upload_to='midia/')),
            ],
        ),
    ]
